
= La guilde des développeurs/développeuses illustres

== Présentation

Le but du projet est de réaliser à plusieurs, à distance, des projets de développement (jeux/autre) publiés sous licence libre sans but lucratif. Tout le monde peut rejoindre la guilde, sans condition de niveau (dans le but d'apprendre) ou de temps (beaucoup de communication différée).

"Développeur/développeuse" est ici utilisé au sens large (pas uniquement pour la programmation) pour désigner toute personne qui contribue aux projets, peu importe la nature de la contribution.

Le projet est avant tout une expérience afin de voir comment ça peut fonctionner et les difficultés que ça implique au niveau individuel ou général (motivation, etc). Même dans le cas où aucun projet n'aboutirait, il est intéressant d'essayer pour mettre en évidence ces difficultés.

La guilde a pour objectif d'avoir une organisation plutôt démocratique (ex: proposer et voter des idées), le tout étant géré/maintenu par quelques administrateurs (cumulé au rôle de membre).

.Exemples de fonctions d'administration
* modération (discord/GitHub/etc)
* surveiller les projets et les commits
* appliquer les propositions votées (ex: créer un projet/supprimer un projet)
* gérer/organiser (ex: la guilde, l'e-mail, des serveurs, etc)

Rejoindre la guilde -> https://discord.gg/HPpTRnt[discord].

== Règles

* le respect
* les moyens de communication non persistants (chat sans historique, vocal) peuvent être utilisés, mais les informations importantes doivent être retranscrites de manière persistante
* les repositories ne doivent pas être modifiés autrement que par des commits successifs (ex: pas de push forcé), seuls les administrateurs peuvent si besoin réctifier une erreur (ce qui nécessitera un reset de tous les repositories locaux); les informations des commits doivent donc être exactes (e-mail, nom) et aucune donnée sensible ne doit être push

== Procédures

=== Vote


NOTE: Les votes consistent globalement à "`appliquer une règle de tiers d'écart sur les votes en deux phases,  conclu par un tirage au sort`".

* les administrateurs démarrent des votes quand demandé/nécessaire; tous les votes doivent être précédés d'une phase de discussion
* après un certains temps (à la discrétion des administrateurs pour le moment) les votes sont comptabilisés; les options qui sont retenues vérifient une condition: `valid_option(votes): votes >= ceil(2/3*max)`
+
[NOTE]
====
`max` est le nombre maximum de votes pour une option, le but de cette règle étant de départager les options avec une certaine marge pour éviter qu'un seul vote soit trop significatif et fasse basculer le résultat
====
* si une seule option subsiste, le vote est terminé, sinon un second vote est effectué entre les options valides
* s'il reste encore plus d'une option valide, le résultat est tiré au sort

== Informations

* le repository de https://github.com/guild-of-illustrious-developers/test[test] peut être utilisé pour faire des tests de commit ou autre
